---
- hosts: linux
  tasks:
  - name: Copy Checkmk agent installer.
    copy:
      src: check-mk-agent_2.0.0p22-1_all.deb
      dest: /tmp/check-mk-agent_2.0.0p22-1_all.deb
      mode: 0644

  - name: Install Checkmk agent.
    apt:
      update_cache: true
      cache_valid_time: 3600
      deb: /tmp/check-mk-agent_2.0.0p22-1_all.deb
      state: present
