---
- hosts: linux
  tasks:
  - name: Uninstall Checkmk agent.
    apt:
      name: check-mk-agent
      state: absent

  - name: Remove Checkmk agent installer.
    file:
      path: /tmp/check-mk-agent_2.0.0p22-1_all.deb
      state: absent

  - name: Inspect check-mk package.
    shell:
      set -o pipefail
      apt list --installed | grep check-mk
    failed_when: false
    changed_when: false
    register: check_result

  - name: Check if check-mk package is absent.
    assert:
      that:
        - "check_result.rc == 1"
      fail_msg: "The package is still installed."
      success_msg: "The package was successfully removed."
